
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sapi
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: billipoul/ac2:latest
    networks:
      - default  # Certifique-se de que está usando a rede adequada
    environment:
      DB_HOST: database
    ports:
      - "9091:8080"
volumes:
  db-volume: